// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/TouchSky.h"
#include "Commands/driveWithJoystick.h"
#include "Commands/moveArm.h"
#include "Commands/moveFinger.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    // frc::Command* m_arm = new moveArm(setWinchPosButton, 1);
    joystick1.reset(new frc::Joystick(0));
    setWinchPosButton.reset(new frc::JoystickButton(joystick1.get(), 3));
    setWinchPosButton->WhenPressed(new moveFinger(3));
    // setWinchPosButton->WhenReleased()
    touchSkyButton.reset(new frc::JoystickButton(joystick1.get(), 1));
    touchSkyButton->WhenPressed(new moveArm(touchSkyButton, 1));


    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("driveWithJoystick", new driveWithJoystick());
    frc::SmartDashboard::PutData("TouchSky", new TouchSky());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystick1() {
   return joystick1;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
